### ISSUE TITLE
Issue in patch instance

### ISSUE THREAD

**Issue by vdroy97** [HoLLy-HaCKeR/EazFixer#2]
Unhandled Exception: System.NotSupportedException: Wrong MethodAttributes or CallingConventions for DynamicMethod. Only public, static, standard supported
   at System.Reflection.Emit.DynamicMethod.CheckConsistency(MethodAttributes attributes, CallingConventions callingConvention)
   at System.Reflection.Emit.DynamicMethod.Init(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] signature, Type owner, Module m, Boolean skipVisibility, Boolean transparentMethod, StackCrawlMark& stackMark)
   at System.Reflection.Emit.DynamicMethod..ctor(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] parameterTypes, Type owner, Boolean skipVisibility)
   at Harmony.DynamicTools.CreateDynamicMethod(MethodBase original, String suffix)
   at Harmony.MethodPatcher.CreatePatchedMethod(MethodBase original, List`1 prefixes, List`1 postfixes, List`1 transpilers)
   at Harmony.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at Harmony.PatchProcessor.Patch()
   at Harmony.HarmonyInstance.<PatchAll>b__6_0(Type type)
   at Harmony.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at Harmony.HarmonyInstance.PatchAll(Assembly assembly)
   at EazFixer.Harmony.Patch() in C:\test\EazFixer\EazFixer\Harmony.cs:line 13
   at EazFixer.Program.Main(String[] args) in C:\test\EazFixer\EazFixer\Program.cs:line 19

**Comment by HoLLy-HaCKeR** [comment]
Hmm, seems like a Harmony issue, this never happened to me. Just to be sure, what is your OS?

**Comment by vdroy97** [comment]
Win - 10 64 bit

**Comment by HoLLy-HaCKeR** [comment]
Yeah, Harmony bug, I'm using an outdated branch so it's likely fixed in the main one. It's strange that I don't have any problems with this. Once [this PR] is merged, I will switch to the main branch.

**Comment by vdroy97** [comment]
ok i fixed now, but string fixer not work properly

Executing memory patches...
Initializing modules...
Processing...
Cleanup...

Applied patches:
StringFixer: Failed
ResourceResolver: Success

Writing new assembly...
DONE
Press any key to exit...

**Comment by HoLLy-HaCKeR** [comment]
What did you "fix"? If it broke the StringFixer, it may have been required functionality.

**Comment by B0u3z1z1** [comment]
i need full version plz 
send me here if you can
my mail: medhacked@gmail.com
thnks

**Comment by HoLLy-HaCKeR** [comment]
Going to close this since I got no response, and I was never able to repro this.
